name: "Cache"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC

jobs:
  cache-builds:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-latest
          - system: x86_64-darwin
            runner: macos-13
          - system: aarch64-darwin
            runner: macos-14
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: gleam-overlay
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - name: Build all Gleam versions for ${{ matrix.system }}
      run: |
        # Get all available versions from gleam_hashes.json
        VERSIONS=$(jq -r 'keys[] | select(. != "latest" and . != "nightly")' gleam_hashes.json)
        
        # Build each version for the current system
        for version in $VERSIONS; do
          nix build --system ${{ matrix.system }}
        done
        
        # Build latest and nightly
        nix build --system ${{ matrix.system }} 
        nix build --system ${{ matrix.system }}
