name: Update Gleam

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 6:00 UTC
  workflow_dispatch: # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python scripts/fetch_gleam_releases.py

      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code gleam_hashes.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gleam_hashes.json
          git commit -m "chore: update Gleam hashes"
          git push
